#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=96:00:00
#SBATCH --mem=64GB
#SBATCH --job-name=gridVOC
#SBATCH --gres=gpu:1
#SBATCH --mail-type=END
#SBATCH --mail-user=<netid>@nyu.edu
#SBATCH --output=<your log path>/batch-%j.log

RUNDIR=$HOME/translation/
cd $RUNDIR

module load anaconda3/5.3.0

. /share/apps/anaconda3/5.3.0/etc/profile.d/conda.sh
conda activate mt


for USE in True False
do
	for VOC in 25000 50000 100000
	do
	    python grid_VOC.py -c user_mt3685 -m CNNAttn_Tanh -v $VOC -u $USE
	done
done
